name: Version without GAEN dependencies

on:
    push:
        tags:
            - 'v*\+nogaen'

jobs:
    build:
        name: "Build app"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Retrieve latest SDK release
              uses: dsaltares/fetch-gh-release-asset@master
              with:
                  repo: c4dt/dp3t-sdk-android
                  version: latest
                  file: sdk-libs.zip

            - name: Setup SDK
              run: |
                  rm -f ./app/libs/*
                  unzip sdk-libs.zip -d ./app/libs/

            - name: Build
              run: ./gradlew assembleProdRelease -PkeystoreFile=c4dt.store -PkeystorePassword=${{ secrets.KEYSTORE_PASSWORD }} -PkeyAliasPassword=${{ secrets.KEY_ALIAS_PASSWORD }}

            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: ${{ contains(github.ref, 'alpha') }}

            - name: Upload APK as release artifact
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./app/build/outputs/apk/prod/release/app-prod-release.apk
                  asset_name: swisscovid.apk
                  asset_content_type: application/zip
